// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPI_ProgramacionIII.DBContexts;

#nullable disable

namespace TPI_ProgramacionIII.Migrations
{
    [DbContext(typeof(ECommerceContext))]
    [Migration("20231108214925_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("TPI_ProgramacionIII.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Name = "Remera Fiberton",
                            Price = 1250m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 7,
                            Name = "Remera Loren",
                            Price = 1320m,
                            Stock = 15
                        });
                });

            modelBuilder.Entity("TPI_ProgramacionIII.Data.Entities.SaleOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("SaleOrders");
                });

            modelBuilder.Entity("TPI_ProgramacionIII.Data.Entities.SalerOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaleOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleOrderId");

                    b.ToTable("SaleOrderLines");
                });

            modelBuilder.Entity("TPI_ProgramacionIII.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TPI_ProgramacionIII.Data.Entities.Admin", b =>
                {
                    b.HasBaseType("TPI_ProgramacionIII.Data.Entities.User");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Email = "ngomez@gmail.com",
                            LastName = "Gomez",
                            Name = "Nicolas",
                            Password = "123456",
                            UserName = "ngomez_admin",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 5,
                            Email = "bdiaz@gmail.com",
                            LastName = "Bruno",
                            Name = "Diaz",
                            Password = "123456",
                            UserName = "bdiaz",
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("TPI_ProgramacionIII.Data.Entities.Client", b =>
                {
                    b.HasBaseType("TPI_ProgramacionIII.Data.Entities.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Client");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ngomez@gmail.com",
                            LastName = "Gomez",
                            Name = "Nicolas",
                            Password = "123456",
                            UserName = "ngomez_cliente",
                            Address = "Rivadavia 111"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Jperez@gmail.com",
                            LastName = "Perez",
                            Name = "Juan",
                            Password = "123456",
                            UserName = "jperez",
                            Address = "J.b.justo 111"
                        },
                        new
                        {
                            Id = 3,
                            Email = "jgarcia@gmail.com",
                            LastName = "Garcia",
                            Name = "Jose",
                            Password = "123456",
                            UserName = "jgarcia",
                            Address = "San Martin 111"
                        });
                });

            modelBuilder.Entity("TPI_ProgramacionIII.Data.Entities.SaleOrder", b =>
                {
                    b.HasOne("TPI_ProgramacionIII.Data.Entities.Client", "Client")
                        .WithMany("SalesOrders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TPI_ProgramacionIII.Data.Entities.SalerOrderLine", b =>
                {
                    b.HasOne("TPI_ProgramacionIII.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI_ProgramacionIII.Data.Entities.SaleOrder", "SaleOrder")
                        .WithMany("SalesLines")
                        .HasForeignKey("SaleOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SaleOrder");
                });

            modelBuilder.Entity("TPI_ProgramacionIII.Data.Entities.SaleOrder", b =>
                {
                    b.Navigation("SalesLines");
                });

            modelBuilder.Entity("TPI_ProgramacionIII.Data.Entities.Client", b =>
                {
                    b.Navigation("SalesOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
